### ISSUE TITLE
How can I adapt the Chinese acoustic model?

### ISSUE THREAD

**Issue by lixiang1991** [syl22-00/pocketsphinx.js-zh-tdt_sc_8k#1]
Maybe the acoustic model in pocketsphinx is different from the acoustic model in sphinx.I seem to have seen you say that, but I can't find it now.
And I have a try.
I download the zh_broadcastnews_16k_ptm256_8000.tar.bz2 from [zh_broadcastnews_16k_ptm256_8000.tar.bz2 ](https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/Mandarin/)
And then embed them by the following code:

```
import os
import os.path

rootdir = "D:\DevelopDocument\python"  

for parent, dirnames, filenames in os.walk(rootdir):
    for filename in filenames:  
        if filename.find('.') < 0 or filename.find('.params')>-1:
            os.system(
                'python "E:\Program Files\Emscripten\emscripten\\1.35.0\\tools\\file_packager.py" pocketsphinx.js --embed ' + filename + ' --js-output=' + filename + ".js")
```

When I load the files `[ "feat.params.js", "mdef.js", "means.js", "noisedict.js", "sendump.js", "transition_matrices.js", "variances.js",
        "dict.js", "lm.js" ]` in the html, it doesn't work and tells the error.

```
ERROR: "fe_interface.c", line 269: Upper frequency 6855.5 is higher than samprate/2 (4000.0)
pocketsphinx.js:50 Uncaught abort() at Error
    at stackTrace (http://192.168.1.124:8081/sphinx_js/pocketsphinx.js:1:21245)
    at Object.abort (http://192.168.1.124:8081/sphinx_js/pocketsphinx.js:50:34083)
    at _abort (http://192.168.1.124:8081/sphinx_js/pocketsphinx.js:1:375639)
    at Dv (http://192.168.1.124:8081/sphinx_js/pocketsphinx.js:37:232)
    at Xd (http://192.168.1.124:8081/sphinx_js/pocketsphinx.js:5:30102)
    at Array.Ke (http://192.168.1.124:8081/sphinx_js/pocketsphinx.js:5:51449)
    at Array.Le (http://192.168.1.124:8081/sphinx_js/pocketsphinx.js:5:51526)
    at Fz (http://192.168.1.124:8081/sphinx_js/pocketsphinx.js:37:79871)
    at Recognizer.constructor_body (http://192.168.1.124:8081/sphinx_js/pocketsphinx.js:50:68163)
    at Recognizer.<anonymous> (http://192.168.1.124:8081/sphinx_js/pocketsphinx.js:50:65963)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

The application works successfully using the acoustic model which is supplied in this repository.
But the recognition result is not accurate, so I would like to do acoustic model adaptation.
Maybe I should do some work on the original acoustic model files rather than  the `.js` files.
Is that correct?
Where can I get them?
Thanks for any help!

**Comment by syl22-00** [comment]
I guess from the file name that the acoustic model you are trying to use was trained on 16kHz audio. So you should set `outputSampleRate: 16000`, or not set it at all as it is the default value. The model in this repo was an old model for Chinese trained on 8kHz.

**Comment by lixiang1991** [comment]
Thanks,you are right.

**Comment by xiaosdawn** [comment]
Hi, if I have a relatively large acoustic model trained from standard materials, say broadcast news recordings, and a small model trained from recording of specific fields, i.e. telephone speech or even speech control for machines. Is there a way to combine and adapt them to generate a new model? 
Any advises or ideas will be appreciate! Thanks.
